import json
from typing import Dict, Any
from ...models.schema import ReverseSchemaOutput

class ReverseSchemaWeapon:
    """
    Weapon 5: Reverse-Schema Generator
    Generates target SQL DDL schemas, Prisma ORM definitions, Pydantic v2 models,
    and TypeScript interfaces directly from the parsed 11-column enterprise schema.
    """

    def generate_schemas(self, table_name: str = "recast_enterprise_records") -> ReverseSchemaOutput:
        # 1. Production PostgreSQL / MySQL DDL
        sql_ddl = f"""-- =========================================================================
-- RECAST ENTERPRISE REVERSE-SCHEMA MIGRATION DDL
-- Auto-generated by Recast-AI Autonomous Agent
-- Target Engine: PostgreSQL 14+ / MySQL 8.0+ Compatible
-- =========================================================================

CREATE TABLE IF NOT EXISTS {table_name} (
    -- Column 1: Deterministic Enterprise Identifier
    record_id VARCHAR(64) PRIMARY KEY,

    -- Column 2: Classified Entity Type
    entity_type VARCHAR(32) NOT NULL CHECK (entity_type IN ('INDIVIDUAL', 'ENTERPRISE', 'VENDOR', 'LOGISTICS_HUB')),

    -- Column 3: Normalized Legal / Trading Name
    full_name_clean VARCHAR(255) NOT NULL,

    -- Column 4: Validated Tax Identifier (PAN / GSTIN / TIN)
    tax_id VARCHAR(64) DEFAULT 'NOT_PROVIDED',

    -- Column 5: Primary Premise & Street
    address_line1 TEXT NOT NULL,

    -- Column 6: Locality, Sector, Landmark
    address_line2 TEXT,

    -- Column 7: Normalized City
    city VARCHAR(128) NOT NULL,

    -- Column 8: Standardized State / Province
    state_province VARCHAR(128) NOT NULL,

    -- Column 9: Postal / PIN Code
    postal_code VARCHAR(32) NOT NULL,

    -- Column 10: E.164 Contact & Email
    contact_normalized VARCHAR(128) DEFAULT 'NOT_PROVIDED',

    -- Column 11: Multimodal AI Confidence Score
    confidence_score NUMERIC(4, 3) NOT NULL CHECK (confidence_score >= 0.0 AND confidence_score <= 1.0),

    -- Enterprise Audit & Ingestion Metadata
    lineage_hash VARCHAR(64) NOT NULL,
    migration_timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Performance Indexes for High-Throughput Analytics
CREATE INDEX IF NOT EXISTS idx_{table_name}_city_state 
    ON {table_name} (city, state_province);

CREATE INDEX IF NOT EXISTS idx_{table_name}_tax_id 
    ON {table_name} (tax_id);

CREATE INDEX IF NOT EXISTS idx_{table_name}_entity_type 
    ON {table_name} (entity_type);
"""

        # 2. Prisma ORM Schema
        prisma_schema = f"""// =========================================================================
// RECAST PRISMA ORM SCHEMA
// Generated by Recast-AI Agent for Type-Safe Database Access
// =========================================================================

generator client {{
  provider = "prisma-client-js"
}}

datasource db {{
  provider = "postgresql"
  url      = env("DATABASE_URL")
}}

enum EntityType {{
  INDIVIDUAL
  ENTERPRISE
  VENDOR
  LOGISTICS_HUB
}}

model RecastRecord {{
  recordId          String      @id @map("record_id") @db.VarChar(64)
  entityType        EntityType  @map("entity_type")
  fullNameClean     String      @map("full_name_clean") @db.VarChar(255)
  taxId             String      @default("NOT_PROVIDED") @map("tax_id") @db.VarChar(64)
  addressLine1      String      @map("address_line1") @db.Text
  addressLine2      String?     @map("address_line2") @db.Text
  city              String      @map("city") @db.VarChar(128)
  stateProvince     String      @map("state_province") @db.VarChar(128)
  postalCode        String      @map("postal_code") @db.VarChar(32)
  contactNormalized String      @default("NOT_PROVIDED") @map("contact_normalized") @db.VarChar(128)
  confidenceScore   Decimal     @map("confidence_score") @db.Decimal(4, 3)
  
  lineageHash       String      @map("lineage_hash") @db.VarChar(64)
  createdAt         DateTime    @default(now()) @map("migration_timestamp")

  @@index([city, stateProvince])
  @@index([taxId])
  @@map("{table_name}")
}}
"""

        # 3. Pydantic v2 Model
        pydantic_model = f"""# =========================================================================
# RECAST ENTERPRISE PYDANTIC V2 MODEL
# =========================================================================
from typing import Literal, Optional
from datetime import datetime
from pydantic import BaseModel, Field

class RecastEnterpriseModel(BaseModel):
    record_id: str = Field(..., description="Unique enterprise identifier")
    entity_type: Literal["INDIVIDUAL", "ENTERPRISE", "VENDOR", "LOGISTICS_HUB"]
    full_name_clean: str = Field(..., min_length=1, max_length=255)
    tax_id: str = Field(default="NOT_PROVIDED")
    address_line1: str = Field(..., description="Door/House/Street")
    address_line2: Optional[str] = Field(None, description="Locality/Landmark")
    city: str = Field(..., max_length=128)
    state_province: str = Field(..., max_length=128)
    postal_code: str = Field(..., max_length=32)
    contact_normalized: str = Field(default="NOT_PROVIDED")
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    lineage_hash: str = Field(...)
    migration_timestamp: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        from_attributes = True
        str_strip_whitespace = True
"""

        # 4. TypeScript Interface
        typescript_interface = """// =========================================================================
// RECAST ENTERPRISE 11-COLUMN TYPESCRIPT INTERFACE
// =========================================================================

export type EntityClassification = 'INDIVIDUAL' | 'ENTERPRISE' | 'VENDOR' | 'LOGISTICS_HUB';

export interface CleanEnterpriseRecord11Col {
  /** 1. Unique deterministic enterprise ID (REC-XXXX-XXXX) */
  record_id: string;

  /** 2. Classified entity category */
  entity_type: EntityClassification;

  /** 3. Normalized Title-Cased Name */
  full_name_clean: string;

  /** 4. Validated PAN, GSTIN, TIN, or Tax ID */
  tax_id: string;

  /** 5. Premise, House, Plot, Building, Street, Gali */
  address_line1: string;

  /** 6. Locality, Sector, Landmark, Mohalla */
  address_line2: string;

  /** 7. Normalized City / Municipal Region */
  city: string;

  /** 8. Standardized State / Province */
  state_province: string;

  /** 9. Validated 6-digit PIN / Postal code (Self-Healed if missing) */
  postal_code: string;

  /** 10. E.164 phone (+91...) and sanitized email address */
  contact_normalized: string;

  /** 11. Multimodal AI confidence rating (0.00 to 1.00) */
  confidence_score: number;

  /** Enterprise metadata */
  self_healed_fields?: string[];
  vernacular_terms_resolved?: string[];
  raw_source_snippet?: string;
  record_hash?: string;
}
"""

        # 5. JSON Schema Draft-07
        json_schema = json.dumps({
            "$schema": "http://json-schema.org/draft-07/schema#",
            "title": "RecastCleanRecord11Col",
            "type": "object",
            "required": [
                "record_id", "entity_type", "full_name_clean", "tax_id",
                "address_line1", "address_line2", "city", "state_province",
                "postal_code", "contact_normalized", "confidence_score"
            ],
            "properties": {
                "record_id": {"type": "string"},
                "entity_type": {"type": "string", "enum": ["INDIVIDUAL", "ENTERPRISE", "VENDOR", "LOGISTICS_HUB"]},
                "full_name_clean": {"type": "string"},
                "tax_id": {"type": "string"},
                "address_line1": {"type": "string"},
                "address_line2": {"type": "string"},
                "city": {"type": "string"},
                "state_province": {"type": "string"},
                "postal_code": {"type": "string"},
                "contact_normalized": {"type": "string"},
                "confidence_score": {"type": "number", "minimum": 0.0, "maximum": 1.0}
            }
        }, indent=2)

        return ReverseSchemaOutput(
            sql_ddl=sql_ddl,
            prisma_schema=prisma_schema,
            pydantic_model=pydantic_model,
            typescript_interface=typescript_interface,
            json_schema=json_schema
        )
